### PR TITLE
ref(nvim): move all logic into editor crate

### PR DESCRIPTION
**Pull request by tami5**
This PR aims to refactor editor crate and move all logic editor crate, (including lua/ folder). This refactor may require adding additional RPC methods like get targets, scheme etc.

## TODOs 
- [x] Move logging and logger functionality to editor crate.
- [x] Setup a broadcast server where client can listen and handle
- [x] Remove nvim-rs crate from daemon crate.
- [x] Try using raw_fd for passing messages
- [x] Implement NvimGlobal::log function
- [x] Fix attached client to same broadcast server don't recieve messsages
- [x] Fix connected notification not delivered to new client sharing same project
- [x] Specialize some message to be delivered to a single instance instead of all instance.
- [x] Reimplement logger buffer logic

### CODE REVIEW

**Comment by tami5** [comment]
I've considered @noib3, [nvim-oxi] in this refactor, as it will greatly simpilfy logic and render custom mlua extensions for neovim runtime absolute, thoguh I'm little hesitant for few reasons 
  1. Tokio Runtime and async, proto required client to be async, and not sure if async is supported in [nvim-oxi] as of now.
  2. serlialize and desrialize types, currently, I'm implementing mlua traits in both proto and
     editor crate so I'm not sure how would this translate to [nvim-oxi]
[nvim-oxi]:https://github.com/noib3/nvim-oxi

**Comment by noib3** [comment]
1. the functions exposed by oxi are in general not async because the Neovim C api itself is not async. Using the Neovim api via Lua through the `mlua` crate doesn't magically make it async either;

2. you'll be able to pass to (and retrieve from) the Neovim api any Rust type that implements `Serialize` or `Deserialize`, just like you can w/ `mlua`.

In general there shouldn't be anything you can do through `mlua` that you can't do w/ oxi. The opposite might not be true.

**Comment by tami5** [comment]
> 1. the functions exposed by oxi are in general not async because the Neovim C api itself is not async. Using the Neovim api via Lua through the `mlua` crate doesn't magically make it async either;

hmm I believe mlua uses lua coroutines to provide async functions. 

> 2. you'll be able to pass to (and retrieve from) the Neovim api any Rust type that implements `Serialize` or `Deserialize`, just like you can w/ `mlua`.
> 
> In general there shouldn't be anything you can do through `mlua` that you can't do w/ oxi. The opposite might not be true.

The opposite is not true indeed .. uhh I will skip switching to oxi on this PR, perhaps in future PR I will tackle it. 

Thanks @noib3 for your input

**Comment by noib3** [comment]
> I believe mlua uses lua coroutines to provide async functions

you could do the same directly from Rust by spawning a new task on the current thread with any async runtime, e.g. tokio.

**Comment by tami5** [comment]
> > I believe mlua uses lua coroutines to provide async functions
> 
> you could do the same directly from Rust by spawning a new task on the current thread with any async runtime, e.g. tokio.

hmm you mean using block_on, I tried that while hacking and trying to make my tokio async values yield in lua runtime. It blocked my nvim instance. but perhaps, I need to confirm that

**Comment by noib3** [comment]
I'll try to include an example on how to use async functionalities from Rust before releasing on crates.io

**Pull request merged**
